//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularzStudenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class praktykanci
    {
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string uczelnia { get; set; }
        public string jezyki { get; set; }
        public Nullable<System.DateTime> dataPraktyk { get; set; }
        public string rokStudiow { get; set; }
        public Nullable<bool> elektrotechnika { get; set; }
    }
}
